<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Presentation" nsURI="www.presentation.com">
  <eClassifiers xsi:type="ecore:EClass" name="Package">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Class">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//ClassType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//Property"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ClassType">
    <eLiterals name="null"/>
    <eLiterals name="presentationGroup" value="1"/>
    <eLiterals name="inputForm" value="2"/>
    <eLiterals name="presentationPage" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Property">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//PropertyType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//Property"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PropertyType">
    <eLiterals name="null"/>
    <eLiterals name="inputForm" value="1"/>
    <eLiterals name="presentationGroup" value="2"/>
    <eLiterals name="presentationAlternatives" value="3"/>
    <eLiterals name="iteratedPresentationGroup" value="4"/>
    <eLiterals name="presentationPage" value="5"/>
    <eLiterals name="text" value="6"/>
    <eLiterals name="picture" value="7"/>
    <eLiterals name="mediaObject" value="8"/>
    <eLiterals name="inputText" value="9"/>
    <eLiterals name="fileUpload" value="10"/>
    <eLiterals name="selection" value="11"/>
    <eLiterals name="button" value="12"/>
    <eLiterals name="anchor" value="13"/>
  </eClassifiers>
</ecore:EPackage>
