<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Requirement" nsURI="www.requirement.com">
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="packagedElement" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UseCase">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Actor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Generalization">
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" lowerBound="1" eType="#//Actor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="general" lowerBound="1"
        eType="#//Actor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessingUseCase" eSuperTypes="#//UseCase"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrowsingUseCase" eSuperTypes="#//UseCase"/>
  <eClassifiers xsi:type="ecore:EClass" name="Extension" eSuperTypes="#//Association"/>
  <eClassifiers xsi:type="ecore:EClass" name="Association">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputPins" upperBound="-1"
        eType="#//InputPin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputPins" upperBound="-1"
        eType="#//OutputPin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputPin" eSuperTypes="#//Pin"/>
  <eClassifiers xsi:type="ecore:EClass" name="OutputPin" eSuperTypes="#//Pin"/>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectFlow">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DisplayAction" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="displayPins" upperBound="-1"
        eType="#//DisplayPin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interactionPins" upperBound="-1"
        eType="#//InteractionPin"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//DisplayActionType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="validated" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserAction" eSuperTypes="#//Action"/>
  <eClassifiers xsi:type="ecore:EClass" name="SystemAction" eSuperTypes="#//Action"/>
  <eClassifiers xsi:type="ecore:EClass" name="Activity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CentralBufferNode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" lowerBound="1" eType="#//Activity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputPins" upperBound="-1"
        eType="#//InputPin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputPins" upperBound="-1"
        eType="#//OutputPin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lowerValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upperValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Include" eSuperTypes="#//Association"/>
  <eClassifiers xsi:type="ecore:EClass" name="NavigationAction" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="behavior" eType="#//Activity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" lowerBound="1" eType="#//Activity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DecisionNode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityParameterNode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityFinalNode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InitialNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="DisplayPin" eSuperTypes="#//Pin"/>
  <eClassifiers xsi:type="ecore:EClass" name="InteractionPin" eSuperTypes="#//Pin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//InteractionPinType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DisplayActionType">
    <eLiterals name="null"/>
    <eLiterals name="form" value="1"/>
    <eLiterals name="group" value="2"/>
    <eLiterals name="alternatives" value="3"/>
    <eLiterals name="iteration" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DisplayPinType">
    <eLiterals name="null"/>
    <eLiterals name="text" value="1"/>
    <eLiterals name="image" value="2"/>
    <eLiterals name="media" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="InteractionPinType">
    <eLiterals name="null"/>
    <eLiterals name="text" value="1"/>
    <eLiterals name="selection" value="2"/>
    <eLiterals name="file" value="3"/>
  </eClassifiers>
</ecore:EPackage>
